

import os
Import('env')

## Add Shared library and wrapper_*.hh path.
## You also can use the  LIBS parameter to specify 
##  the dynamic link library you want to link, when
##  compiling with SCons. For example:
##  $ scons LIBS=example LIBPATH=/path/to/library

env.Append(CPPPATH=[Dir('.').srcnode()])
env.Append(LIBS=['VerilatorChecksumXcel'])
env.Prepend(LIBPATH=Dir('.').srcnode())

env.Append(LINKFLAGS=['-Wl,-rpath,' + str(Dir('.').srcnode())])

env.Append(CPPDEFINES=['VM_SC=0', 'VM_TRACE=1','VL_THREADED=0'])